name: Build & Deploy Hugo to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.9'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Deploy to main
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.My_GITHUB_TOKEN }}
          branch: main
          directory: public
          commit_message: "Deploy site via GitHub Actions"
